name: Decrypt esigncert and Create Release

on:
  push:
    branches:
      - main  # Trigger on push to main branch (adjust as needed)
  workflow_dispatch:  # Allow manual triggering

jobs:
  decrypt-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any additional dependencies if needed
          # pip install <package>

      # Run the decryption script
      - name: Run decryption script
        run: |
          python decrypted_output.py .
        working-directory: ${{ github.workspace }}

      # Create a release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Decrypted Files Release ${{ github.run_number }}
          draft: false
          prerelease: false

      # Upload decrypted files as release assets
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in decrypted_output/*.p12 decrypted_output/*.mobileprovision; do
            if [ -f "$file" ]; then
              echo "Uploading $file..."
              gh release upload v${{ github.run_number }} "$file" --repo ${{ github.repository }}
            else
              echo "No files found to upload."
            fi
          done
        working-directory: ${{ github.workspace }}